# fly.toml app configuration file generated for devcal-node-demo on 2025-01-08T21:08:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devcal-node-demo'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 9001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
